_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": forget_test/epoch_coarse_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": forget_test/epoch_fine_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/it_fine_loss
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": iteration
              "6":
                - 3
              "7": []
            - "1": forget_train/it_train_loss
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_test/it_fine_accuracy
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/epoch_coarse_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_test/it_coarse_loss
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/epoch_train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/epoch_fine_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/it_coarse_loss
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/it_fine_accuracy
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_test/it_fine_loss
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_test/it_coarse_accuracy
              "5": 5
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_test/epoch_coarse_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": forget_train/it_coarse_accuracy
              "5": 5
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 7
                - 13
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
